name: Slack Workflow Run

on:
  workflow_call:
    inputs:
      conclusion:
        required: true
        type: string
      workflow-name:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  slack-workflow-run:
    name: Send Notification
    runs-on: ubuntu-latest
    steps:
      - name: Setup Message and Channels
        id: setup
        shell: bash
        run: |
          # TODO: change to 'eng-idx-alerts,release-management-alerts'
          CHANNEL="eng-idx-alerts"
          echo "channel=${CHANNEL}" >> $GITHUB_OUTPUT

          FULL_MESSAGE="nothing"
          if [[ "${{ inputs.conclusion }}" =~ ^(success)$ ]]; then
            FULL_MESSAGE=":white_check_mark: ${MESSAGE} :relaxed:"
          elif [[ "${{ inputs.conclusion }}" =~ ^(failure|timed_out)$ ]]; then
            FULL_MESSAGE=":fire: ${MESSAGE} :disappointed:"
          fi
          echo "message=${FULL_MESSAGE}" >> $GITHUB_OUTPUT
        env:
          MESSAGE: "*${{ inputs.workflow-name }}* ${{ inputs.conclusion }} on ${{ inputs.branch }} - <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|Run#${{github.event.workflow_run.id}}>"

      - name: Post Slack Notification
        uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
        if: ${{ steps.setup.outputs.message != 'nothing' }}
        with:
          channel-id: ${{ steps.setup.outputs.channel }}
          slack-message: "${{ steps.setup.outputs.message }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
